CREATE TABLE pre_departure."PNR_Report_IT" (
  id          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "PNR"       text,
  "JSON"      jsonb,
  "Status"    text,
  reason      text,
  reported_by text,
  reported_on text,
  created_at  timestamp with time zone
);

CREATE POLICY "authenticated_all_PNR_Report_IT" ON pre_departure."PNR_Report_IT"
  TO authenticated
  USING (true)
  WITH CHECK (true);

ALTER TABLE pre_departure."PNR_Report_IT"
  OWNER TO payload_app;

ALTER TABLE pre_departure."PNR_Report_IT"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE pre_departure."PNR_Report_IT"
  ADD CONSTRAINT "PNR_Report_IT_pkey" PRIMARY KEY (id);

GRANT INSERT, SELECT ON pre_departure."PNR_Report_IT" TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON pre_departure."PNR_Report_IT" TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON pre_departure."PNR_Report_IT" TO service_role;